dbPagos-cnx: Server=tcp:pago-servicios-favoritos.database.windows.net,1433;Initial Catalog=pagos-db;Persist Security Info=False;User ID=bootcamp;Password=B00tcamp2022;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

