dbVenta-cnx: Server=tcp:pago-servicios-favoritos.database.windows.net,1433;Initial Catalog=pago-servicios-favoritos-db;Persist Security Info=False;User ID=bootcamp;Password=B01tcamp2022;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
url-base-servicio-stock: https://localhost:7065

